"""Phase-1 rice pest rules derived from india_rice_pest_thresholds_FINAL_v2.csv.

No unsupported universal weather thresholds are invented. Source risk_rule/notes
remain authoritative for relationship-based evidence.
"""

RISK_BANDS = {"LOW": (0,24), "MEDIUM": (25,49), "HIGH": (50,74), "VERY HIGH": (75,100)}

AVAILABLE_FEATURES = {
    "temperature_current", "relative_humidity_current", "recent_rainfall",
    "forecast_rainfall", "days_after_sowing", "growth_stage", "season",
    "state", "location",
}

CURRENTLY_UNAVAILABLE_FEATURES = {
    "sunshine_hours", "daily_tmin", "daily_tmax", "morning_rh",
    "evening_rh", "lagged_weather", "historical_weekly_weather_relationships",
    "soil_moisture_for_thrips_rule",
}

PETS = {
    'BROWN_PLANTHOPPER_(BPH)': {'pest_name': 'Brown Planthopper (BPH)', 'scientific_name': 'Nilaparvata lugens', 'season': 'Kharif', 'location': 'Delhi, India', 'evidence_period': '2017-2018', 'growth_stage_or_timing': 'First observed 29 SMW; peak 43 SMW (2017 study)', 'DAT_min': None, 'DAT_max': None, 'temp_min_c': None, 'temp_max_c': None, 'rh_min_pct': None, 'rh_max_pct': None, 'rain_min_mm': None, 'rain_max_mm': None, 'rain_window_days': None, 'sunshine_min_hr': None, 'sunshine_max_hr': None, 'weather_lag_weeks': '0, 1 and 2', 'evidence_relationship': 'Positive association with Tmax and morning RH (current, 1-lag, 2-lag); negative association with Tmin and rainfall (current, 1-lag, 2-lag); RH1, RH2 and sunshine were important predictors.', 'threshold_type': 'forecasting_relationship', 'risk_rule': 'Do not use a universal numeric threshold; compare current/lagged Tmax, Tmin, RH1, RH2, rainfall and sunshine with the study relationship.', 'evidence_level': 'HIGH', 'source_id': 'BPH-Delhi-2020', 'source': 'Rice brown planthopper prediction model with sweepnet catches (Indian Journal of Entomology, 2020)', 'source_url': 'https://doi.org/10.5958/0974-8172.2020.00141.8', 'notes': "Original file's 25–30°C, RH≥80% and rain=true rule is not retained because the cited study does not establish those as universal thresholds."},
    'YELLOW_STEM_BORER_(YSB)': {'pest_name': 'Yellow Stem Borer (YSB)', 'scientific_name': 'Scirpophaga incertulas', 'season': 'Kharif + Rabi', 'location': 'Mandya, Karnataka, India', 'evidence_period': '1991-2005 data; 7 years used for model, 8-year validation', 'growth_stage_or_timing': 'Peak-catch timing studied from July onward; weather effects occurred at several preceding weeks', 'DAT_min': None, 'DAT_max': None, 'temp_min_c': None, 'temp_max_c': None, 'rh_min_pct': None, 'rh_max_pct': None, 'rain_min_mm': None, 'rain_max_mm': None, 'rain_window_days': None, 'sunshine_min_hr': None, 'sunshine_max_hr': None, 'weather_lag_weeks': 'Multiple preceding weeks', 'evidence_relationship': 'YSB peak catches were significantly related to Tmax (Oct week 3), Tmin (Nov week 1), rainfall (Oct week 2), RH1 (Nov week 4), RH2 (Nov week 1) and sunshine (Oct week 4). Stepwise model retained Tmin, rainfall and RH1. Model validation R²=0.90.', 'threshold_type': 'forecasting_relationship', 'risk_rule': 'Use lagged weekly Tmin, rainfall and morning RH as the primary environmental evidence; do not impose a universal temperature/RH/rainfall range.', 'evidence_level': 'HIGH', 'source_id': 'YSB-Mandya-2015', 'source': 'Development of weather based rice yellow stem borer prediction model for the Cauvery command rice areas, Karnataka, India', 'source_url': 'https://doi.org/10.1080/23311932.2014.995281', 'notes': 'The study explicitly states pest-weather relationships are empirical/location-specific.'},
    'YELLOW_STEM_BORER_(YSB)': {'pest_name': 'Yellow Stem Borer (YSB)', 'scientific_name': 'Scirpophaga incertulas', 'season': 'Kharif/Rabi/Summer', 'location': 'Mandya, Karnataka, India', 'evidence_period': '2022-2023', 'growth_stage_or_timing': 'Dead heart peak 30–50 DAT; white ear peak 80–100 DAT; exact peak SMW varied by season', 'DAT_min': '30.0', 'DAT_max': '100.0', 'temp_min_c': None, 'temp_max_c': None, 'rh_min_pct': None, 'rh_max_pct': None, 'rain_min_mm': None, 'rain_max_mm': None, 'rain_window_days': None, 'sunshine_min_hr': None, 'sunshine_max_hr': None, 'weather_lag_weeks': 'Season-dependent', 'evidence_relationship': 'Kharif: dead heart/white ear peaks correlated positively with Tmax and negatively with Tmin. Rabi: morning RH and sunshine positive; Tmin and afternoon RH negative. Summer: Tmin, rainy days, rainfall and afternoon RH positive.', 'threshold_type': 'growth_stage_and_relationship', 'risk_rule': 'Use DAT/growth phase to distinguish dead-heart and white-ear risk, then apply season-specific weather relationships; no universal numeric threshold.', 'evidence_level': 'HIGH', 'source_id': 'YSB-Mandya-2024', 'source': 'Influence of weather parameters on the seasonal occurrence of paddy yellow stem borer, Indian Journal of Agricultural Sciences', 'source_url': 'https://epubs.icar.org.in/index.php/IJAgS/article/view/147332', 'notes': 'Useful for linking environmental risk to crop timing, but numeric weather cutoffs are not reported as universal thresholds.'},
    'RICE_LEAF_FOLDER': {'pest_name': 'Rice Leaf Folder', 'scientific_name': 'Cnaphalocrocis medinalis', 'season': 'Kharif', 'location': 'Middle Gangetic Plains / Varanasi, India', 'evidence_period': '2018-2020', 'growth_stage_or_timing': 'Infestation began 31 SMW; peak 38-39 SMW; highest damage at booting stage', 'DAT_min': None, 'DAT_max': None, 'temp_min_c': None, 'temp_max_c': None, 'rh_min_pct': None, 'rh_max_pct': None, 'rain_min_mm': None, 'rain_max_mm': None, 'rain_window_days': None, 'sunshine_min_hr': None, 'sunshine_max_hr': None, 'weather_lag_weeks': None, 'evidence_relationship': 'Rainfall, morning RH, average RH and Tmax had significant positive influence on leaf-folder infestation.', 'threshold_type': 'forecasting_relationship', 'risk_rule': 'Increase environmental risk when Tmax, rainfall and RH move in the direction reported by the study, especially around booting; do not use universal numeric cutoffs.', 'evidence_level': 'HIGH', 'source_id': 'LF-Varanasi-2024', 'source': 'Impact of crop phenology and environmental factors on rice leaf folder infestation in middle gangetic plains of India', 'source_url': 'https://doi.org/10.55362/IJE/2024/4318', 'notes': 'The study provides strong timing/relationship evidence but not a universal Tmax/RH/rainfall threshold.'},
    'GALL_MIDGE': {'pest_name': 'Gall Midge', 'scientific_name': 'Orseolia oryzae', 'season': 'Kharif', 'location': 'India', 'evidence_period': None, 'growth_stage_or_timing': None, 'DAT_min': None, 'DAT_max': None, 'temp_min_c': None, 'temp_max_c': None, 'rh_min_pct': None, 'rh_max_pct': None, 'rain_min_mm': None, 'rain_max_mm': None, 'rain_window_days': None, 'sunshine_min_hr': None, 'sunshine_max_hr': None, 'weather_lag_weeks': None, 'evidence_relationship': None, 'threshold_type': None, 'risk_rule': None, 'evidence_level': None, 'source_id': None, 'source': None, 'source_url': None, 'notes': 'No sufficiently specific Indian evidence was verified for the numeric thresholds in the original CSV. Do not use the original 20–26°C / RH≥85% / 30 mm rule.'},
    'RICE_BUG_(GUNDHI_BUG)': {'pest_name': 'Rice Bug (Gundhi Bug)', 'scientific_name': 'Leptocorisa acuta', 'season': 'Kharif', 'location': 'India', 'evidence_period': None, 'growth_stage_or_timing': 'Panicle/grain stage is biologically plausible, but no numeric threshold retained here', 'DAT_min': None, 'DAT_max': None, 'temp_min_c': None, 'temp_max_c': None, 'rh_min_pct': None, 'rh_max_pct': None, 'rain_min_mm': None, 'rain_max_mm': None, 'rain_window_days': None, 'sunshine_min_hr': None, 'sunshine_max_hr': None, 'weather_lag_weeks': None, 'evidence_relationship': None, 'threshold_type': None, 'risk_rule': None, 'evidence_level': None, 'source_id': None, 'source': None, 'source_url': None, 'notes': 'No sufficiently specific Indian weather-threshold evidence was verified for the original 25–32°C / RH 70–90% / rain rule.'},
    'GREEN_LEAF_HOPPER': {'pest_name': 'Green Leaf Hopper', 'scientific_name': 'Nephotettix spp.', 'season': 'Kharif', 'location': 'Chinsurah, West Bengal, India', 'evidence_period': 'NCIPM multi-location forewarning', 'growth_stage_or_timing': 'Mid-to-late season; Chinsurah peaks around 39–42 SMW', 'DAT_min': None, 'DAT_max': None, 'temp_min_c': '33.0', 'temp_max_c': '34.0', 'rh_min_pct': '55.0', 'rh_max_pct': '92.0', 'rain_min_mm': None, 'rain_max_mm': '10.0', 'rain_window_days': '7.0', 'sunshine_min_hr': '6.0', 'sunshine_max_hr': '9.0', 'weather_lag_weeks': None, 'evidence_relationship': 'High GLH severity when >4 of the listed weekly weather criteria were satisfied. Criteria are weekly means/totals.', 'threshold_type': 'location_specific_weekly_rule', 'risk_rule': 'At Chinsurah, count satisfied weekly criteria: Tmax 33–34, Tmin 22–25, RH morning 89–92, RH evening 55–65, weekly rainfall <10 mm, sunshine 6–9 h/day. >4 criteria = high severity; 4 = moderate; <4 = low.', 'evidence_level': 'HIGH', 'source_id': 'GLH-NCIPM', 'source': 'NCIPM Weather based prediction for rice insect pests', 'source_url': 'https://nriipm.res.in/NCIPMPDFs/Publication/InsectPestsRice_.pdf', 'notes': 'The individual RH ranges are not represented perfectly by a single RHmin/RHmax field; use risk_rule as the authoritative condition.'},
    'WHITEBACKED_PLANTHOPPER_(WBPH)': {'pest_name': 'Whitebacked Planthopper (WBPH)', 'scientific_name': 'Sogatella furcifera', 'season': 'Kharif', 'location': 'India', 'evidence_period': None, 'growth_stage_or_timing': None, 'DAT_min': None, 'DAT_max': None, 'temp_min_c': None, 'temp_max_c': None, 'rh_min_pct': None, 'rh_max_pct': None, 'rain_min_mm': None, 'rain_max_mm': None, 'rain_window_days': None, 'sunshine_min_hr': None, 'sunshine_max_hr': None, 'weather_lag_weeks': None, 'evidence_relationship': None, 'threshold_type': None, 'risk_rule': None, 'evidence_level': None, 'source_id': None, 'source': None, 'source_url': None, 'notes': 'No sufficiently specific Indian evidence was verified for the original 25–28°C / RH 75–90% rule. Do not use it as a universal threshold.'},
    'RICE_THRIPS': {'pest_name': 'Rice Thrips', 'scientific_name': 'Stenchaetothrips biformis', 'season': 'Rabi + early Kharif nursery', 'location': 'India', 'evidence_period': None, 'growth_stage_or_timing': None, 'DAT_min': None, 'DAT_max': None, 'temp_min_c': None, 'temp_max_c': None, 'rh_min_pct': None, 'rh_max_pct': None, 'rain_min_mm': None, 'rain_max_mm': None, 'rain_window_days': None, 'sunshine_min_hr': None, 'sunshine_max_hr': None, 'weather_lag_weeks': None, 'evidence_relationship': None, 'threshold_type': None, 'risk_rule': None, 'evidence_level': None, 'source_id': None, 'source': None, 'source_url': None, 'notes': 'No sufficiently specific Indian evidence was verified for the original 30–35°C / RH 20–49% / soil-moisture rule. Soil moisture is also outside the current hardware scope.'},
}

# Engineering weights for Phase 1 only; these are NOT source-provided weights.
PHASE1_WEIGHTS = {
    "temperature": 0.25, "humidity": 0.25, "rainfall": 0.20,
    "growth_stage": 0.15, "days_after_sowing": 0.15,
}

def classify_risk(score):
    if score is None: return None
    score=max(0.0,min(100.0,float(score)))
    if score <= 24: return "LOW"
    if score <= 49: return "MEDIUM"
    if score <= 74: return "HIGH"
    return "VERY HIGH"

def pest_rule(name):
    key=name.upper().replace(" ","_").replace("-","_")
    if key not in PETS: raise KeyError(f"Unknown pest: {name}")
    return PETS[key]
